__author__ = 'Lain'

BLOCK_SIZE = 20;
FIGURE_TEMPLATE_SIZE = 4;

DEFAULT_BACKGROUND_COLOR = "lavender";
DEFAULT_FILLED_BLOCK_COLOR = "sky blue";
DEFAULT_BORDER_COLOR = "gray";

DEFAULT_FIGURE_COLOR = DEFAULT_FILLED_BLOCK_COLOR;
DEFAULT_FIGURE_TIP_COLOR = DEFAULT_BACKGROUND_COLOR;